format = """
$time\
[](bg:#DA627D fg:#9A348E)\
$os\
$username\
[](fg:#DA627D bg:#FCA17D)\
$directory\
[](fg:#FCA17D bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$elixir\
$elm\
$golang\
$nodejs\
$ruby\
$rust\
[](fg:#06969A bg:#33658A)\
$docker_context\
[](fg:#33658A)
[ ](bg:#382B4B fg:#9A348E)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#DA627D fg:#382B4B"
style_root = "bg:#DA627D fg:#382B4B"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#DA627D fg:#382B4B"
disabled = true # Disabled by default

[directory]
style = "bg:#FCA17D fg:#382B4B"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
disabled = true
symbol = " "
style = "bg:#33658A fg:#382B4B"
format = '[ $symbol$context ]($style)'

[elixir]
symbol = "󰖌 "
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol($version) ]($style)'

[ruby]
symbol = " "
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol($version) ]($style)'

[elm]
symbol = " "
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#86BBD8 fg:#382B4B"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#86BBD8 fg:#382B4B"
format = '[$all_status $ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#06969A fg:#382B4B"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#9A348E fg:#382B4B"
format = '[ $time ]($style)'
